### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ltjax** [arximboldi/lager#1]
hey juanpe! license seems to be a bit unclear right now. the top level file says MIT, while the sources say GPL3. That's not intentional, is it?

**Comment by arximboldi** [comment]
It is a trick to now sue you all and get all software in the world be FREE!!! MUAHAHAHAHA! :smiling_imp: 

Yeah, I rushed through it it seems I forgot to change most files. I will fix it right now, thanks for noticing and bringing that up!

**Comment by arximboldi** [comment]
Done!

Btw, the `atria::funken` module is the other library that I mentioned that uses Clojure-inspired "lenses/cursors" to provide "observable property views" on a value-based "single root" data model. The documentation is a bit rough but maybe the unit tests help you understand. Let me know if you would like me to explain more about it: https://github.com/Ableton/atria

**Comment by ltjax** [comment]
Thanks!

Yea, I had a short look at the library, and it looks kinda what I envisioned when we talked; a wrapper that makes changes in the state observable. Tell me if I got that totally wrong.
Anyways, after thinking about it for a while, I think we can do better by doing it almost exactly like react-redux. That wouldn't be that intrusive and you can implement it as an extension to lager as it is now.
I'm thinking of something like this:
binder.connect([](auto const& model_or_submodel) {return model.whateverstatemycontrolcaresabout;}, myWidget::handleNewData, std::equal<>());

The way I'd implement it is to add a new view into lager that keeps track of the last two states. For each "connection", the first part of that statement above "projects" a part of the old and new state and compares them using the third parameter that's defaulted to std::equal. If the comparison fails, it executes the "handleNewData". if you compose that structure in multiple levels, you can even make it hierarchical.
The comparator is configurable so you can trade update accuracy for speed. For example with immer vectors, you could add a comparator that just looks if the internal structure is the same but does not look into the elements if it isn't, i.e. that comparator allows false negatives at the price of updating your UI too often.
What do you think?

**Comment by arximboldi** [comment]
Hi Marius,

Sorry for the delayed reply, it's been a bit of a crazy week for me.
Here are some thoughts.

> Yea, I had a short look at the library, and it looks kinda what I
> envisioned when we talked; a wrapper that makes changes in the state
> observable. Tell me if I got that totally wrong.  Anyways, after
> thinking about it for a while, I think we can do better by doing it
> almost exactly like react-redux. That wouldn't be that intrusive and
> you can implement it as an extension to lager as it is now.
>
> I'm thinking of something like this:
>
> binder.connect([](auto const& model_or_submodel) {return model.whateverstatemycontrolcaresabout;}, myWidget::handleNewData, std::equal<>());
>
> The way I'd implement it is to add a new view into lager that keeps
> track of the last two states. For each "connection", the first part of
> that statement above "projects" a part of the old and new state and
> compares them using the third parameter that's defaulted to
> std::equal. If the comparison fails, it executes the
> "handleNewData". if you compose that structure in multiple levels, you
> can even make it hierarchical.

Yeah, actually 'funken' is itself quite similar to what you are
proposing, but it does a bit more.  My concern with the binder
abstraction you propose here is that it is so thin that I'm unsure to me
whether it provides any advantage over "doing it manually".  It seems to
me more or less the same amount of code than doing:

   auto view = [&,last_model=model_t{}] (model_t const& new_model) {
       if (last_model.whateverstatemycontrolcaresabout != new_model.whateverstatemycontrolcaresabout)
           myWidget.handleNewData(new_model.whateverstatemycontrolcaresabout);
       // ... more similar checks like that
       last_model = new_model;
   }

What I like about this approach is the high expliciteness of control,
i.e. less callbacky.  There is slightly less repetition in your
approach, but it seems to me that it is still a constant factor amount
of repetition.  But maybe I didn't fully undestand it...

With regards to the nature of 'funken', while I envision ways to make it
work with 'lager', it was conceived before I was much into Elm/Redux but
more into Clojure's Om and Reagent.  It inherits a lot of its
"cursor"/"functional lens" approach.  For full credit, it is derived
from an initial implementation in Clojure by @brentshields who got me
into Clojure and has done a lot of great work towards "value based
architectures."

The goal is to allow a "traditional" object-based UI to have a "data
oriented" API without 1) being coupled to physical data model and 2)
decoupling mutation from updates.  The goal was to have an underlying
"immutable" value-based data model, where the old value is preserved
during updates.  It achieves so by doing something
that looks a lot like a "functional lens".  However, the setter of the
functional lens is somewhat stateful, but less stateful than the typical
setter, because the update is not visible until it is "committed".  In
many applications, for example, it make sense to just commit at 60 Hz.
In this sense, it has what is often called an "epochal time model"

For example, let's say you are implementing a toggle button, you can do
so like this:

    class my_toggle_button : widget
    {
       funken::inout<bool> checked;
       funken::watcher watcher;
       
    public:
       my_toggle_button(funken::inout<bool> data)
         : checked{data}
       {
         auto on_update = [this] (bool newv) {
             this->set_color(newv ? '#f00' : '#333');
         }; 
         watcher = funken::watch(checked, [=] (bool oldv, bool newv) {
             on_update(newv);
         });
         on_update(data.get());
       }

       void on_click() override {
           checked.set(!checked);
       }
    };

Now let's say you are implementing a DAW (you know, that's been my
business for a while :)  You may have a data model that is like this:

    struct track {
        bool mute;
        ...
    }
    
    struct song {
        immer::vector<track> tracks;
        int solo_track_idx;
        ...
    }

Now at the root of your application you are goint to have the "single
atom" state:

    auto state = funken::state<song>{};

And now you can build your UI by projecting the data model into the
widgets:

    auto tracks_inout = funken::attred(state, &song::tracks); // can be erased to funken::inout<immer::vector<track>>
    for (auto idx = size_t{0}; idx < tracks.get().size(); ++idx) {
        auto track_inout = funken::atted(tracks_inout, idx); // can be erased to funken::inout<track>
        // ...
        auto track_mute_button = toggle_button{
            funken::atted(track_inout, &track::mute)
        };
        auto track_solo_button = toggle_button{
            funken::xformed(song,
               map([idx] (const song& s) -> bool {   // getter proj
                   return s.solo_track_idx == idx;
               }),
               map([idx] (song s, bool v) -> song {  // setter proj
                   s.solo_track_idx = v ? idx : -1;
                   return s;
               }));
        };
        // ...
    }

Then somewhere in the vsync callback, ui event post-handler, or
something:

    funken::commit(state);

(Disclaimer: I acknowledge there are problems with that data-model,
e.g. using indexes for identity, but I'd talk about that some other
time)

The cool thing is that the widgets are still "old school", so it is
almost trivial to reuse Qt, WxWidgets or whatever you prefer.  The
"inout<>" (there is also "in<>" or "out<>") looks like a typical observable
property you have in Qt (Q_PROPERTY) and may other frameworks.  However,
it is not backed by real data, but just projections.  This means that it
can be bound "logically", see for example the 'track_solo_button',
without creating "state synchronization" problems.  Also, the epochal
time model means that even though we use setters to modify the model,
the problem of "setter composition" (i.e. setters triggering callbacks
on intermediate states) is mostly avoided.  Finally, the data-model is
fully value based, so it can still be sent for serialization to another
thread, etc, etc.  Also, since the update propragation model is fully
based on value based comparisons, we can "set()" at any level of the
tree, for example, I can fully replace the document by calling
'state.set(...)' and only things that actually changed would be notified...

Am I making sense?

At some point I should write or talk about this model... but the
application that we were building with it never exited prototype stage
so I'd like to gain more experience with it maybe... also I'd change quite
a few things syntactically.  Plus, semantically, a few things I would
change too in a world were a C++ React/Reagent exists... (I have sketches
for a C++ Reagent-like API that I could share with you some day :-)

> The comparator is configurable so you can trade update accuracy for
> speed. For example with immer vectors, you could add a comparator that
> just looks if the internal structure is the same but does not look
> into the elements if it isn't, i.e. that comparator allows false
> negatives at the price of updating your UI too often.  What do you
> think?

One note about comparing immer vectors: comparing an immer vector is
proportional to the amount of change between the vectors.  This is:

    auto v0 = immer::vector<T>{  ...a million elements... };
    auto v1 = v0.set(42, T{...});
    if (v0 != v1) {
       ...
    }

The operations in `v0 != v1` are:

   - pointer equal comparisons:  up to 32 * (log_32(n) - 1)
   - std::equals<T> comparisons: up to 32

This is, it is "effectively O(1)".

When fully replacing a vector though, that is of course O(n), but in
that case probably you may need a O(n) UI update too (with probably
higher constant too) so it is most probably gonna be irrelevant.


Ok, that's enough for today :-)  I'm also gonna reopen the issue to have
the conversation more accessible.

Cheers!

  JP

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es
