### ISSUE TITLE
Combining cursors

### ISSUE THREAD

**Issue by altschuler** [arximboldi/lager#116]
I have something like this model:
```
struct thing {
    std::string id;
    std::string name;
}

struct model {
    immer::map<std::string, thing> things;
    std::optional<std::string> selected_id;
}
```

I'm trying to make a cursor that gives me the currently selected `thing`, based on the `things` and `selected_id` fields, because I want to `watch` without having to do the lookup logic.

So I've tried the following approach (`_store` is a `lager::store` with the model)

```
        auto selected_thing =
                lager::with(_store[&model::things], _store[&model::selected_id])
                        .xform(zug::map([](auto things, auto selected_id) {
                            std::cout << "in xform" << std::endl;
                            return selected_id.has_value() ? std::make_optional(things[selected_id.value()]) : std::nullopt;
                        }))
                        .make();

        lager::watch(selected_thing, [&](auto thing) {
            std::cout << "in watch" << std::endl;
        });
```

This prints `"in xform"` once, and never `"in watch"`. Coming from the Rx world, I'm thinking of `lager::with` as something like the [combine latest](http://reactivex.io/documentation/operators/combinelatest.html) operator, but that might not be the case?

Is there something obvious wrong with the code above?

PS. I kind of wanted to use the `at` "operator", but I couldn't think of a way to use a reader as the lookup value. Also, I have a feeling some of this could be simplified; I'm all ears :)

**Comment by arximboldi** [comment]
What is the scope of `selected_thing`?

In Lager, the `watch(...)` is bound to the concrete reader *object* it's called on. The usual solution is to turn `selected_thing` into a member of whatever class you are in there.

This is so in order to make it easier write typical UI components, ensuring the watches outlive the context in which they are created, and avoiding too much "connection management" logic. This is however the number one cause that I get from newcomers and not-so-newcomers as "this doesn't work!" so maybe I should really reconsider this!

**Comment by altschuler** [comment]
Right, that worked. It makes sense, and I think it's also a matter of being a C++ newcomer. I'll add a note in the docs under cursors and do a PR, that could hopefully help a bit at least :)

Thank you!

**Comment by arximboldi** [comment]
Awesome, thank you! <3

**Comment by arximboldi** [comment]
Also, wrt your code example, I just noticed that you do `.xform(zug::map(...))`, which now can just be `.map(...)`. The latter is simply an alias for the former, for convenience. There's also `.filter()`.
