### ISSUE TITLE
Dependency on Zug

### ISSUE THREAD

**Issue by Louis-Simon22** [arximboldi/lager#17]
Hi, real quick I managed to install the package locally but it won't run because of a dependency on Zug. After looking around in the code I found it was this package https://github.com/arximboldi/zug. There is no documentation on the page though, should I install that package locally in the same way as well?

**Comment by arximboldi** [comment]
Yes, thanks for the awareness. I should update the README soon. That package is since very recently required. You can install it normally via CMake or if you are using Nix you can create a shell expression like this (this is what I use for the `nix-shell` in Lager):

```
  zug = stdenv.mkDerivation rec {
    name = "zug-${version}";
    version = "git-${commit}";
    commit = "5b72389901844ddaca1fb63e44d41f77a6165c2a";
    src = fetchFromGitHub {
      owner = "arximboldi";
      repo = "zug";
      rev = commit;
      sha256 = "1r62khc0fn5a10h138i2jvmf9qlbs1q7kqxvx380ilcqhl32z2jw";
    };
    nativeBuildInputs = [ cmake ];
    meta = with stdenv.lib; {
      homepage = "http://sinusoid.es/zug";
      description = "Transducers for C++";
      license = licenses.lgpl3;
    };
};
```

Lager also has Bazel support and it works automatically there.

**Comment by Louis-Simon22** [comment]
I wrote PKGBUILD files for both libraries and got them to compile with cmake.
