### ISSUE TITLE
Maybe not inject event loop

### ISSUE THREAD

**Issue by ltjax** [arximboldi/lager#2]
I don't think you should inject an event loop into the store. As I said at the conference, I think one defining aspect of the UI feedback loop is that it is synchronous. If you want to do async, you should do that in a thunk or another "advanced action-generation step".
Either way, it's kind of orthogonal anyways, and you can put the dispatch call into an event, if you really wanted - without having the event loop as part of the store.

**Comment by arximboldi** [comment]
Marius Elvert <notifications@github.com> writes:

> I don't think you should inject an event loop into the store. As I
> said at the conference, I think one defining aspect of the UI feedback
> loop is that it is synchronous. If you want to do async, you should do
> that in a thunk or another "advanced action-generation step".  Either
> way, it's kind of orthogonal anyways, and you can put the dispatch
> call into an event, if you really wanted - without having the event
> loop as part of the store.

I agree.  The API was evolved organically from the Ewig code.  At the
moment, having the event loop there serves two purposes:

1. Ensuring that the `dispath()` method is thread-safe and that
   the actual update is evaluated in the main UI/thread.

2. Being able to have a `context<Action>` erases the type of the
   underlying async technology and allows and can dispatch asynchronous
   tasks and some other goodies.

To solve problem (1) a more elegant solution than the current one would
be to simply use a "store enhancer", just like we do to enable the
debugger---it could be called `lagger::in_main_loop(event_loop)` for
example.

Solving problem (2) is trickier.  There is some advantage to having this
type erasure, such that generic "thunks"---"effects" in _Lager_ lingo---can
be written that interact with the main loop without really knowing about
the underlying tech.  Examples can be found in Ewig for asynchronous
saving and loading [1].  But maybe this is a minor problem and can be
rather solved with templates where physical decomposition is not
important.

Feel free to sketch some implementation along these lines.  Otherwise I
might try it myself whenever I have time to work on this again.

Thanks!

  JP

[1] File saving and loading:
https://github.com/arximboldi/ewig/blob/master/src/ewig/buffer.cpp#L146
https://github.com/arximboldi/ewig/blob/master/src/ewig/buffer.cpp#L100

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by ltjax** [comment]
Before we dig into the details: Do you think dispatch needs to be thread safe? Because I think this model really needs to be synchronous to work, and that kind of limits the interaction with threads anyways. I do not think thread safety is needed here.
If you need threading in your app, you should make sure the dispatch calls all occur in your UI/main thread anways.
Do you have compelling evidence against that notion?

**Comment by ltjax** [comment]
I'll explore that. I see that the context integration is not trivial.

In the meantime, I stumbled on at least one problem with how the loop is currently integrated. The "posted" lambda captures the action that is passes by-value. That is certainly needed for any kind of asynchronicity, but I want to pass some polymorphic actions where that would slice away my concrete type if done naively (i.e. just using action_base_t as the Action parameter to the store).
Using std::ref should work and I'm currently investigating using a dedicated type-erasuring wrapper that would probably also mitigate this problem. Let's see where this goes..
