### ISSUE TITLE
Trouble with lenses

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#29]
I'm trying to get a lens (or a cursor, really) to an item in a tree:
[code sample](https://gist.github.com/Siapran/08ebeb0dc5e8070da435ab8dbf74dcdc)

I can't seem to compose lenses like I though I'd be able to, am I missing anything?

**Comment by Siapran** [comment]
[error message](https://imgur.com/Jx0mgD2.png)

**Comment by Siapran** [comment]
I tried an alternative implementation for traversing trees: [code sample](https://gist.github.com/Siapran/560353c69f788c29880dd5709e74bd8d)

but I get a whole lot of warnings from this: [build message](https://gist.github.com/Siapran/5f7c29adb2d5eb1935a4d96fe2442b78)

**Comment by arximboldi** [comment]
That does not work because you are returning lenses of different types in the different cases. Note that the type of these "low level" lenses actually are specific to the arguments they are constructed from. There is no way you can resolve this recursive case without some level of type erasure.

The library however does not provide type-erased lenses per-se, even though you could maybe build them using `lens::getset` in combination with `std::function`.

However, maybe what you want to use here is a `cursor`? Cursors are type-erased and provide a bit of a more friendly interface.

**Comment by arximboldi** [comment]
Oh yeah, I see you solved the issue with cursors already :+1:  :slightly_smiling_face:

**Comment by arximboldi** [comment]
About the warning, I am not sure... I do not think it is a problematic one.

**Comment by arximboldi** [comment]
Which compiler are you using?

**Comment by Siapran** [comment]
GCC right now, but I'm planning on porting this to MSVC.

**Comment by arximboldi** [comment]
Lot's of Lager are sadly not compatible with MSVC at the moment, since they depend on `boost::hana` and do a bit of template tricks that MSVC does not like. It could however be made compatible I believe.

**Comment by Siapran** [comment]
are cursors compatible? I'm not planning on using the rest of lager for now (one step at a time, I'm happy I managed to sneak ONE aspect of value oriented design into my company's codebase)

**Comment by Siapran** [comment]
so the only change I had to make to make my code work with MSVC is changing `send_down` to `send_down_t{}` in a couple places in `xform_nodes.hpp`.
everything else seems to run smoothly

**Comment by Siapran** [comment]
so I ended up writing a simple type erased lens based on your suggestions:
[any_lens.hpp](https://gist.github.com/Siapran/8dfc577e69bc33cdc118ff6aebf18242)

**Comment by arximboldi** [comment]
Very cool @Siapran !
