### ISSUE TITLE
How to use external (spaghetti code) libraries?

### ISSUE THREAD

**Issue by lehmanju** [arximboldi/lager#49]
As we are currently implementing a new library (it is mostly finished already) to use in Xournalpp and want to rewrite our main application to use Redux we now have following problems:

**Prerequisites**
- the library is written as normal object oriented code with listeners, getters, setters and inheritance
- the main application is using lager and value oriented state

**Problems**
- how do we guarantee interoperability that is still clean? (i was thinking to use the library as side effect)
- where do we keep the references to our library objects? (this would be in effect dependencies then …)
- what do we do if we get a simple signal from our library that indicates a view rerender without our internal model actually changing because the library state is not directly part of the application state (in value terms)?
- we also want to exchange the renderer for our document dynamically. Rendering is part of the library as well as the document.

**Comment by lehmanju** [comment]
As `store` is connected to our event loop and is therefore effectively single threaded (at least its updating process) one could use move semantics to move our state in and out of the reducers. This would, however, disable time travel and undo/redo which we won't be using anyway. Is this a feasible approach?

**Comment by lehmanju** [comment]
Suppose we have a move only state, it's copy constructor is deleted. Furthermore, state updates are

**Comment by lehmanju** [comment]
(Sry accidentally closed this)

Maybe it is also possible to implement some kind of copy-on-write mechanism? We then have a `struct` somewhere in our state tree that only copies the whole library state if it is somehow notified of its copying. When it is only moved the state transfers ownership. I am not quite sure about the details of such an approach but it would certainly not break the pattern and as "real" copying is actually only needed for debugging and undo/redo this would improve interoperability to existing libraries.

For signals that go out of our library it is actually straightforward to create simple fields that represent a signal being emitted. The view then simply just listens for change on those fields.

**Comment by arximboldi** [comment]
It is hard to tell just in the abstract.

I think what you hint at in your auto-responses is a good approach: keep the library out of the model, interact with it via effects, make it visible via dependencies.

One way you can think of that library as an external service, e.g. imagine you have a REST API to a remote service. You would use the value-based model as a local cache for rendering and local manipulation, and use effects to talk to the service when needed, then integrate what comes back from it in the model.

Now, depending on the nature of your library that could maybe be prohibitive, or lead to too much boilerplate, it's hard to tell in the abstract.

Making the model move-only could maybe work, but it would require changes in Lager, since it now assumes things are cheap-deep copyable. One thing you can try is to implement real "copy on write", this is: to have the library state somehow boxed and deep-copy it only when you need to modify it.

**Comment by lehmanju** [comment]
Thanks for your reply!

I managed to find a structure that works with our application. I think even if you use no external library at all you have to make compromises at some point.

Here is some context:

Our library manages the object tree that you can see in a Xournalpp document. It also renders those objects into pixelbuffers. It is actually not that bad of an idea to use it as server (using effects and dependencies) and manipulate the document via its functions. The problem then was to notify our view to redraw its contents. I decided to register the view as client as well, so it gets notified when it has to update its document representation. This only applies for the widget that directly displays the document, every other widget should work with the central lager store. So our main widget effectively reacts to a state change in the library, a state change in the application state and will additionally have a small state itself. As drawing lines will have to be without much input lag and must be directly visible on the widget, this will happen in the widget itself. I will probably model this "soft view state" as unidirectional itself, but it makes no sense to dispatch every pointer event through the main hub and reproducing a previous state with pointer elements even though your pen is not touching the surface. So we let the user draw directly on the widget but as soon as he lifts the pen, i.e. he ends his current action, we will dispatch this change through the main hub and update our library model.

**Comment by arximboldi** [comment]
I think that makes sense!

You can use `lager::state<>` and `lager::cursor` to still use the local state in the same way you observe the central state with `lager::store<>`/`lager::reader<>` with the additional convenience that you have `.set()` instead of having to go through actions.

I do agree that it makes sense to keep some of the state more local and use actions/reducers for document-wide operations (particularly, stuff that needs to be registered in the undo system) and compound business-logic stuff. Where to draw the line exactly of course requires nuance and trial and errors, but the tools are there and it seems that you are exploring the design space successfully :)

One of the advantages indeed of cursors also is that the API allows you to start with state in the leafs of your system, and then incrementally unify these states by moving it up in the hierarchy and passing it down with projected cursors, allowing to refactor later without too much hassle!

**Comment by arximboldi** [comment]
Btw @lehmanju, feel free to also point me to branches where you are doing this work, I can take a look and give further feedback if I find time.

Most of the projects using Lager until now are proprietary projects. I'd be happy to reference this work in my talks so people can see an example of a well architected open-source project using the library.

Also: it seems to me that Xournalapp is volunteer based mostly, right? If this is otherwise commercial work, I'd suggest supporting Lager by joining one of the tiers on Github Sponsors or opening a consulting contract with me :smile:

**Comment by arximboldi** [comment]
Btw: I've noticed that you are releasing Xournalpp for Windows? What are you using to compile there now? AFAIK Lager doesn't fully work on MSVC...

**Comment by lehmanju** [comment]
@arximboldi yes, this project is completely open source and voluntarily managed by mostly computer science students (including myself ;).

You can find the current state in our main repository in the rewrite branch. But using this as reference for future talks brings a big responsibility for us.

**Comment by arximboldi** [comment]
Cool, congrats on pushing forward such a nice piece of software then!

Also, of course if you are too shy about it I don't need to mention it on talks, but I thought you'd appreciate the publicity :slightly_smiling_face: It seems anyways that you are putting good thought into the design and writing good code!
