### ISSUE TITLE
Integrating with a QML application

### ISSUE THREAD

**Issue by SimonMarynissen** [arximboldi/lager#86]
I am trying to build a QML application using lager. Looking at the different sources (lager documentation, talks on lager/immer/ewig), there are multiple ways to do this. What would be the most idiomatic way to incorporate the lager architecture into a QML application. It might be a good idea to put in to the documentation, which I am willing to do once I know the answer to my question.

**Comment by arximboldi** [comment]
Yes, that's true. I think also some of the idiomatic patterns have been evolving.

I can tell you though that my biggest projects with Lager are actually using QML, so it is particularly well suited for that :smile: 

I think it still depends on what kind of application are you building?

**Comment by SimonMarynissen** [comment]
The application I have in mind is a type of graphical editor, like a CAD. So generally, there is a list of open documents, and some viewers inheriting QQuickFramebufferObject.

**Comment by arximboldi** [comment]
First, I recommend watching this talk: https://www.youtube.com/watch?v=e2-FRFEx8CA

Here is my general structure on a QML application of that kind:

- The "core" of my application is a data-model that does not depend on Qt and that is writte in a Redux style, this I put in a library.
- Then I have a Qt layer that wraps this, I buld this as a C++ QML plugin.
- This QML plugin provides a type `AppModel` or similar that you can instantiate to create and have access to the "core" of the application. This type is implemented in C++ and:
  * Inherits from `event_loop_quick_item`: https://github.com/arximboldi/lager/blob/master/lager/event_loop/qml.hpp
  * Instantiates a `lager::store<...>` for with your application model, action, etc, registered with `with_qml_event_loop`.
  * You can also override the method `step()` to commit additional `lager::state` cursors and perform other kinds of data synchronizations every frame.
  * This object also exposes your data model with other Qt objects (I call them view model) that are created with `lager::reader` cursors coming from the store, and sometimes a `lager::context<...>` with the actions that it needs to perform. These objects are normally "uncreatable" from QML and are just provided from this central root object. These objects expose the data to QML (see `LAGER_QT_READER`/`LAGER_QT_CURSOR` macros for convenience) and provide `Q_INVOKABLE` methods that dispatch actions into the data model in order to modify it.
- The QML plugin sometiems provides also views implemented in C++ for performance reasons, other `QQuickItem` subclasses that take view model objects, connect to the cursors, and do the drawing in a more optimized way. I recently also started using this library for C++ components: https://github.com/QUItCoding/qnanopainter

I hope this helps getting you in the right direction! Of course you can always experiment and try find whatever is most appropriate for your use case.

**Comment by SimonMarynissen** [comment]
Thank you for the information! One thing that's not clear yet is overriding the step method of `event_loop_quick_item`. Could you provide a concrete example of where you would want to do this? Anyway, I will work on a small example that is a bit more complex than the todo example that you could add to the repository.

**Comment by arximboldi** [comment]
> One thing that's not clear yet is overriding the step method of event_loop_quick_item. Could you provide a concrete example of where you would want to do this?

Unless you use `lager::automatic_tag`, you actually must call `lager::commit(store_)` in this `step` function. Make sure to also call the `step()` function of the base class (`event_loop_quick_item::step()`) in it before doing other stuff!

There is more stuff you can do here, an example: in one application I have an audio engine. I have a `commit()` function where I exchange event queues to/from the audio and UI threads, and also commit Lager `sensor` and `state` cursors that read data from the audio engine into the UI. I call this method on the `step()` function which gets call approximately on every UI redraw.

> Anyway, I will work on a small example that is a bit more complex than the todo example that you could add to the repository

Oh cool, thank you a lot!
